In [2]:
import pandas as pd

In [120]:
netf = pd.read_csv('netflix_titles/netflix_titles.csv')

In [121]:
netf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [122]:
netf

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [123]:
netf['release_year'].unique()

max_y = netf['release_year'].idxmax()
print(netf.loc[max_y]['release_year'])

min_y = netf["release_year"].idxmin()
print(netf.loc[min_y , "release_year"])

print(netf['release_year'].mean().astype(int))


print(netf["rating"].value_counts())

2021
1925
2014
rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [126]:
# # 11.
netf[netf["type"] == "Movie"]

# # 12.
netf[netf["type"] == "TV Show"]

# # 13.
netf[netf["country"].str.contains("India", na=False)]

# # 14.
netf[netf["country"].str.contains("United States", na=False)]

# 15.
netf[netf['release_year'] > 2018]

# 16.
netf[netf['rating'] == 'TV-MA']

# 17
netf["durTime"] = netf["duration"].str.extract(r"(\d+)").astype("Int64")
netf[(netf["type"] == "Movie") & (netf["durTime"] > 120)]

# 18.
netf[(netf['type'] == 'TV Show') & (netf['durTime'] > 3)]

# 19.
netf['date_addedN'] = pd.to_datetime(netf['date_added'].str.strip())
netf[netf['date_addedN'].dt.year == 2021]

# 20.
netf[netf['title'].str.contains('Love', case=False, na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,durTime,date_addedN
25,s26,TV Show,Love on the Spectrum,NaN,Brooke Satchwell,Australia,"September 21, 2021",2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...,2,2021-09-21
158,s159,Movie,Love Don't Cost a Thing,Troy Byer,"Nick Cannon, Christina Milian, Kenan Thompson,...",United States,"September 1, 2021",2003,PG-13,101 min,"Comedies, Romantic Movies",A nerdy teen tries to make himself cool by ass...,101,2021-09-01
159,s160,Movie,Love in a Puff,Pang Ho-cheung,"Miriam Chin Wah Yeung, Shawn Yue, Singh Hartih...",Hong Kong,"September 1, 2021",2010,TV-MA,103 min,"Comedies, Dramas, International Movies",When the Hong Kong government enacts a ban on ...,103,2021-09-01
206,s207,Movie,"LSD: Love, Sex Aur Dhokha",Dibakar Banerjee,"Nushrat Bharucha, Anshuman Jha, Neha Chauhan, ...",India,"August 27, 2021",2010,TV-MA,112 min,"Dramas, Independent Movies, International Movies",This provocative drama examines how the voyeur...,112,2021-08-27
227,s228,Movie,Really Love,Angel Kristi Williams,"Kofi Siriboe, Yootha Wong-Loi-Sing, Michael Ea...",United States,"August 25, 2021",2020,TV-MA,95 min,"Dramas, Independent Movies, Romantic Movies",A rising Black painter tries to break into a c...,95,2021-08-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8567,s8568,TV Show,The Year of Happiness and Love,NaN,"Amber Kuo, James Wen, Weber Yang, Sonia Sui, N...",Taiwan,"September 1, 2016",2009,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Jiang Chen-bo is a loser without prospects for...,1,2016-09-01
8575,s8576,TV Show,This Is My Love,NaN,"Jin-mo Joo, Sa-rang Kim, Junior, Ja-in Lee, Su...",South Korea,"May 22, 2017",2015,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",A renowned actor who is still pining over the ...,1,2017-05-22
8649,s8650,Movie,Two Lovers and a Bear,Kim Nguyen,"Dane DeHaan, Tatiana Maslany, Gordon Pinsent, ...",Canada,"May 2, 2017",2016,R,95 min,"Dramas, Independent Movies, Romantic Movies",A troubled couple living near the North Pole b...,95,2017-05-02
8721,s8722,TV Show,What Is Love?,NaN,"Chris Wu, Jade Chou, Duncan Lai, King Chin, Ki...",Taiwan,"January 1, 2017",2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A 32-year-old romantic looking for a long-term...,1,2017-01-01
8725,s8726,Movie,What's Up With Love?,"Rudy Soedjarwo, Riri Riza","Dian Sastrowardoyo, Nicholas Saputra, Ladya Ch...",Indonesia,"December 8, 2018",2002,R,110 min,"Dramas, International Movies, Romantic Movies",A popular high school girl strains her relatio...,110,2018-12-08

In [171]:
# 21.
netf['release_year'].value_counts().idxmax()

# 22.
netf['country'].value_counts().idxmax()

# 23.
netf['rating'].value_counts().idxmin()

# 24.
netf.loc[netf['title'].str.len().idxmax(), 'title']

# 25.
netf.loc[netf[netf['type'] == 'Movie']['durTime'].idxmin()]['title']

# 26.
netf.loc[netf[netf["type"] == "Movie"]["durTime"].idxmax()]["title"]

# 27.
netf['director'].value_counts().idxmax()

# 28.
netf['cast'].str.split(',').explode().value_counts().idxmax()

# 29.
netf['listed_in'].str.split(',').explode().value_counts().idxmax()

# 30.
netf['date_addedN'].dt.year.astype('Int64').value_counts().idxmax()

2019

In [ ]:
# 1.
netf[netf['country'].str.contains('India', na=False)]['cast'].str.split(',').explode().value_counts().idxmax()

# 2.
netf[netf['type'] == 'Movie']['listed_in'].str.split(',').explode().str.strip().value_counts().idxmax()

# 4.
netf[netf['type'] == 'TV Show']['date_addedN'].dt.year.astype('Int64').value_counts().idxmax()

# 5.
netf.loc[netf['release_year'].idxmin(), ['title', 'date_added', 'release_year']]

2020

In [224]:
netf.isna().sum()
# netf['director'].fillna('UnknownDirector', inplace=True)

show_id           0
type              0
title             0
director          0
cast            825
country         831
date_added       10
release_year      0
rating            4
duration          3
listed_in         0
description       0
durTime           3
date_addedN      10
dtype: int64

In [221]:
netf['director']

0       Kirsten Johnson
1       UnknownDirector
2       Julien Leclercq
3       UnknownDirector
4       UnknownDirector
             ...
8802      David Fincher
8803    UnknownDirector
8804    Ruben Fleischer
8805       Peter Hewitt
8806        Mozez Singh
Name: director, Length: 8807, dtype: object

In [239]:
netf_10 = netf.loc[0:9]
netf_10.to_json('netflix_titles/data.json', orient='records',  indent=2)

In [258]:
import requests

base_url = "https://api.restcountries.com/countries/v5"

headers = {"Authorization": "Bearer rc_live_35e0adc91c594cbe906c38cd5d943e48"}

response3 = requests.get(base_url, headers=headers)

json_data = response3.json()

data = pd.json_normalize(json_data['data']['objects'])[['names.common', 'names.official' , 'region', 'currencies']].explode('currencies')

data.head()

,names.common,names.official,region,currencies
0,Abkhazia,Republic of Abkhazia,Asia,"{'code': 'RUB', 'name': 'Russian ruble', 'symb..."
1,Afghanistan,Islamic Republic of Afghanistan,Asia,"{'code': 'AFN', 'name': 'Afghan afghani', 'sym..."
2,Albania,Republic of Albania,Europe,"{'code': 'ALL', 'name': 'Albanian lek', 'symbo..."
3,Algeria,People's Democratic Republic of Algeria,Africa,"{'code': 'DZD', 'name': 'Algerian dinar', 'sym..."
4,American Samoa,American Samoa,Oceania,"{'code': 'USD', 'name': 'United States dollar'..."